logging:
  pattern:
    console: "%6relative [%12.12thread] %clr(%5p) %msg%n"
eureka:
  client:
    service-url:
      defaultZone: ${discovery.server}
    register-with-eureka: true
    healthcheck:
      enabled: true
    fetch-registry: true