logging:
  pattern:
    console: "%6relative [%12.12thread] %clr(%5p) %msg%n"
eureka:
  client:
    service-url:
      defaultZone: ${discovery.server:http://127.0.0.1:5555/eureka/}
    register-with-eureka: true
    healthcheck:
      enabled: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10
  server:
    eviction-interval-timer-in-ms: 60000
    renewal-threshold-update-interval-ms: 60000
    enable-self-preservation: false

info:
  app:
    name: ${@project.artifactId@}
    artifact: '@project.artifactId@'
    version: '@project.version@'
    port: ${server.port}
